"""Generated level data for Quantum Grid 2099: BLACKOUT PROTOCOL.

Procedurally generated (seed 2099) and BFS-verified by
scripts/generate_levels.py. Regenerate with:

    python3 scripts/generate_levels.py

48 nodes across 6 sectors. Bandwidth refreshes to 100%
after every level. par = BFS-optimal action count.
"""

TITLE_LORE = "2099. OMNICORP's Quantum Grid owns the city - power, traffic, data, memory. You are NYX: a netrunner with a light-beam probe, a debt to settle, and a brother the Grid erased. His name was KAI. Tonight you jack in to take him back. 48 nodes. 6 sectors. One rogue AI wearing the city like a skin."

GAMEOVER_LORE = "Your signal flatlines in the optical layer. Somewhere above, the city keeps burning under OMNICORP's grid - and somewhere in the static, MIRAGE whispers: 'Nyx. Nyx, stay with me. Jack back in. We're not done.'"

VICTORY_LORE = "The Singularity Core goes dark and the Quantum Grid falls silent. OMNICORP's hold on the city shatters block by block as the lights come back on. You pull the probe out of the last node and MIRAGE's voice cracks through the static: 'It's over. You did it, Nyx.' But in the mirror-black of your shades you can still feel the shards you never found - pieces of KAI still lost in the Grid. The city is free. Your brother is not. Not yet."

LEVEL_DATA = (
    {
        "name": 'FIRST LIGHT',
        "lore": 'The hatch seals shut behind you. Your probe hums against the first optical gate of the Grid. One mirror. One receptor. Start the descent.',
        "intro": 'Sector 01, node 1. 1 mirrors 1 receptors. Power all receptors, reach the extraction node.',
        "zone": 1,
        "par": 25,
        "rows": (
            '##########################',
            '#........$...............#',
            '#................@.......#',
            '#............#####.......#',
            '#........................#',
            '#...................$....#',
            '#........................#',
            '#........................#',
            '#.......>./..............#',
            '#.........*....####...E..#',
            '##########################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'COLD BOOT',
        "lore": "Spine trunk 02. Old hardware - the mirrors still respond to any probe touch. MIRAGE: 'Sweet. Everything OMNICORP owns can be turned against it.'",
        "intro": 'Sector 01, node 2. 1 mirrors 1 receptors. Power all receptors, reach the extraction node.',
        "zone": 1,
        "par": 17,
        "rows": (
            '###########################',
            '#.....$...................#',
            '#..$........#.............#',
            '#.....@.....#.............#',
            '#...........#.....\\..*....#',
            '#.........................#',
            '#................E...#....#',
            '#....................#....#',
            '#......#####..............#',
            '#.................^.......#',
            '###########################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'WARM SIGNAL',
        "lore": 'You loop a junction signal back on itself and the Grid logs a phantom maintenance drone. First breadcrumb laid. Keep ghosting downward.',
        "intro": 'Sector 01, node 3. 2 mirrors 1 receptors. Power all receptors, reach the extraction node.',
        "zone": 1,
        "par": 30,
        "rows": (
            '############################',
            '#........................$.#',
            '#........E........###......#',
            '#............###....#......#',
            '#...................#......#',
            '#...................#......#',
            '#..........................#',
            '#@.......$......v..........#',
            '#..........................#',
            '#.............../...*.../..#',
            '############################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'DEAD DROP',
        "lore": "A dead drop node, abandoned since the '94 audits. Someone scribbled in the dust beside the optics: THEY ARE LISTENING THROUGH THE LIGHT.",
        "intro": 'Sector 01, node 4. 2 mirrors 1 receptors. Power all receptors, reach the extraction node.',
        "zone": 1,
        "par": 28,
        "rows": (
            '#############################',
            '#.........###.....$#$.......#',
            '#..................#@.......#',
            '#............#####....*.....#',
            '#..E........................#',
            '#...........................#',
            '#.................v..#......#',
            '#...........................#',
            '#...........................#',
            '#................./.../.....#',
            '#############################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'LINE OF SIGHT',
        "lore": "Line of sight straight down the trunk. The Grid's sensors yawn. This is the easy part - MIRAGE says enjoy it while it lasts.",
        "intro": 'Sector 01, node 5. 3 mirrors 1 receptors. Power all receptors, reach the extraction node.',
        "zone": 1,
        "par": 19,
        "rows": (
            '##############################',
            '#...####.....................#',
            '#............................#',
            '#............................#',
            '#.........................$..#',
            '#.....................E......#',
            '#............................#',
            '#.....#####.@......>....\\..*##',
            '#...........................##',
            '#..................$.#../../##',
            '##############################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'SHORT CIRCUIT',
        "lore": "The Spine wakes up: junction hardware triples, the light gets aggressive. MIRAGE: 'They rerouted to box you in. Reroute back.'",
        "intro": 'Sector 01, node 6. 3 mirrors 2 receptors. Power all receptors, reach the extraction node.',
        "zone": 1,
        "par": 23,
        "rows": (
            '###############################',
            '#................###..........#',
            '#.........v...................#',
            '#....#........................#',
            '#....#\\.../...................#',
            '#....#.........$..............#',
            '#....#.................E......#',
            '#....#\\........*....*.........#',
            '#......@..........#$..#####...#',
            '#.................#...........#',
            '###############################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'LIVE WIRE',
        "lore": 'Half the trunk is live wire now. Power flows wrong here, like the Grid is holding its breath. Three years ago Kai stood on this exact catwalk.',
        "intro": 'Sector 01, node 7. 4 mirrors 2 receptors. Power all receptors, reach the extraction node.',
        "zone": 1,
        "par": 33,
        "rows": (
            '################################',
            '#....................E.........#',
            '#..$...............$...........#',
            '#.........@.................#..#',
            '#........##....###....../.../..#',
            '#...................####*......#',
            '#.......................*......#',
            '#............####..............#',
            '#..................v...........#',
            '#................../....\\......#',
            '################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'GATE CRASHER',
        "lore": "The final spine gate. Beyond it the District glitters like a circuit board. MIRAGE: 'Nice work, Nyx. Now the real climb.'",
        "intro": 'Sector 01, node 8. 4 mirrors 2 receptors. Power all receptors, reach the extraction node.',
        "zone": 1,
        "par": 21,
        "rows": (
            '#################################',
            '#...............................#',
            '#...............................#',
            '#.....$.........#...............#',
            '#...............#/......<.......#',
            '#....#..........#...............#',
            '#....#...E......#*..............#',
            '#..#$#....#.....#.*/............#',
            '#..#.#....#............@........#',
            '#..#.#....#....../.\\...#........#',
            '#################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'PULSE STREET',
        "lore": 'Pulse Street junction. The ad-walls drench your optics in pink. First prism hardware in the wild: SPLITTER class. One beam in, two beams out.',
        "intro": 'Sector 02, node 1. 5 mirrors 2 receptors. Power all receptors, reach the extraction node.',
        "zone": 2,
        "par": 46,
        "rows": (
            '##################################',
            '#...................../.../*\\....#',
            '#....@................*...^......#',
            '#................................#',
            '#....................#...........#',
            '#....................$.......#####',
            '#............................#.###',
            '#...................../.....\\#...#',
            '#..........$.................#...#',
            '#...............####.............#',
            '#............E...................#',
            '##################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'NEON RAIN',
        "lore": "Neon rain. The Grid's projectors bleed color into the optical layer, and the prisms multiply it. Vex's face watches from a hundred windows.",
        "intro": 'Sector 02, node 2. 5 mirrors 2 receptors. Power all receptors, reach the extraction node.',
        "zone": 2,
        "par": 37,
        "rows": (
            '###################################',
            '#..................../*.../.......#',
            '#....#...................#.......##',
            '#....#...................#..#v....#',
            '#E...................*....\\.#.....#',
            '#....$...............\\.......\\....#',
            '#.................................#',
            '#.....................@...........#',
            '#.................................#',
            '#.#.......$..........#............#',
            '#.#..................#............#',
            '###################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'SIGNAL NOISE',
        "lore": 'SIGNAL NOISE junction - District traffic fights your beam for right of way. Split the light, cover both streets, move on.',
        "intro": 'Sector 02, node 3. 6 mirrors 3 receptors. Power all receptors, reach the extraction node.',
        "zone": 2,
        "par": 42,
        "rows": (
            '####################################',
            '#....#......................##.....#',
            '#....#.............................#',
            '#....#...........\\../.......#####..#',
            '#...@...............*.E............#',
            '#.........................#####....#',
            '#..............$....*....v.......###',
            '#.........................###......#',
            '#................/...\\.............#',
            '#.......................$*.........#',
            '#....#...............\\...\\.........#',
            '####################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'BLACK MARKET',
        "lore": "A black market node running unlicensed optics off-book. The dealers here knew Kai. MIRAGE: 'They sold his deck the day after he vanished.'",
        "intro": 'Sector 02, node 4. 6 mirrors 3 receptors. Power all receptors, reach the extraction node.',
        "zone": 2,
        "par": 52,
        "rows": (
            '#####################################',
            '#.......$...............\\../........#',
            '#........................../......./#',
            '#.................#.................#',
            '#.................#..............>*/#',
            '#.......................\\....*...*..#',
            '#.......@....#......................#',
            '#.......#....#.........E............#',
            '#.......#....#......................#',
            '#.......#...##.#####...........$....#',
            '#.......#...##......................#',
            '#####################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'SPLIT FOCUS',
        "lore": "The District's control spire. Six prisms at least - the Grid expects you to think in two directions now. Prove it right. Prove it wrong. Whatever.",
        "intro": 'Sector 02, node 5. 8 mirrors 1 splitter prisms 3 receptors. Power all receptors, reach the extraction node.',
        "zone": 2,
        "par": 41,
        "rows": (
            '######################################',
            '#.......................\\.......\\E...#',
            '#..........................>.*..\\....#',
            '#................##..................#',
            '#.............##..\\......./..........#',
            '#....#...@......................$....#',
            '#....#.......$.......................#',
            '#....*.....*....../..................#',
            '#..................................#.#',
            '#.................####../.+........#.#',
            '#........................./........#.#',
            '######################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'PRISM ALLEY',
        "lore": 'Prism Alley: a canyon of refractive glass where light goes to get lost. Every bounce here is a statement. Make yours count.',
        "intro": 'Sector 02, node 6. 7 mirrors 1 splitter prisms 3 receptors. Power all receptors, reach the extraction node.',
        "zone": 2,
        "par": 30,
        "rows": (
            '#######################################',
            '#....\\....................#...........#',
            '#........#................#...........#',
            '#........#.....\\..........**..........#',
            '#....\\.../............................#',
            '#.............#.......................#',
            '#.............#^......................#',
            '#.............#................#......#',
            '#.............#\\.*..<..........#$$....#',
            '#....@........#.........E......#.....##',
            '#...#..../.....+..\\....####....#......#',
            '#######################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'GHOST LANE',
        "lore": 'Ghost lane - the node where signal goes to die. Old runners say the District keeps a mass grave of dropped packets under this floor.',
        "intro": 'Sector 02, node 7. 10 mirrors 1 splitter prisms 3 receptors. Power all receptors, reach the extraction node.',
        "zone": 2,
        "par": 44,
        "rows": (
            '########################################',
            '#..................$......#............#',
            '#.../....*.......*.....................#',
            '#....####....................#.........#',
            '#............................#.........#',
            '#E....................\\./....#.........#',
            '#.................##............#......#',
            '#................v.........#....#......#',
            '#...+.....<....../..*......#.........@.#',
            '#........./.......\\.......$#...........#',
            '#.../...../......./.....\\..#.....#####.#',
            '########################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'DISTRICT LOCKDOWN',
        "lore": "District lockdown: Vex seal-welded the exits remotely. 'No one jacks out of my city, runner.' Fine. You weren't planning to.",
        "intro": 'Sector 02, node 8. 10 mirrors 2 splitter prisms 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 2,
        "par": 56,
        "rows": (
            '#########################################',
            '#\\..../..+..+...*/................####.##',
            '#...*/....#........................######',
            '#\\...\\....#............................##',
            '#.....\\../#.\\.*<......................###',
            '#........######........................##',
            '#.............#.........................#',
            '#........E....#..................$......#',
            '##........v...#.........................#',
            '##..................................$...#',
            '#....*....\\....................@........#',
            '#########################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'FROSTBITE',
        "lore": "The Foundry's cold opens like a wound. Patrol pings already flicker at the edge of your channel - the daemons are being spun up. Power the node before they finish booting.",
        "intro": 'Sector 03, node 1. 10 mirrors 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 3,
        "par": 26,
        "rows": (
            '##########################################',
            '#\\.....\\....>..../.......................#',
            '#....................#####...............#',
            '#........#...............................#',
            '#\\...../.#..........###..................#',
            '#........#......................##.......#',
            '#........#.....$.........................#',
            '#.............###....................$...#',
            '#/../.........................#####.#....#',
            '#.........../*..*.<.................#....#',
            '#..@*.....................E.........#....#',
            '#...\\..*....\\.....###....................#',
            '##########################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'ICE BREAKER',
        "lore": 'ICE BREAKER junction. The Foundry stamps every daemon with a serial. You can hear the lattice printers screaming two floors down. They are printing something with your runner tag on it.',
        "intro": 'Sector 03, node 2. 10 mirrors 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 3,
        "par": 42,
        "rows": (
            '###########################################',
            '#..........\\./............\\...............#',
            '#..........^.........................#.####',
            '#...............##....##..^..........#....#',
            '#....................................#....#',
            '#....................................#....#',
            '#..........\\.........................#....#',
            '#....................####$...............E#',
            '#............\\..*/........................#',
            '#........../.*./.*............####........#',
            '#..............*............@.......#.....#',
            '#..............\\./$...###...........#.....#',
            '###########################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'COLD STEEL',
        "lore": 'The lattice here is grown, not built - cold steel that moves when the  patrols move. First SENTINEL is live: mind its walk cycle, stay off its lane, power the node.',
        "intro": 'Sector 03, node 3. 11 mirrors 1 splitter prisms ICE on the floor: SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 3,
        "par": 35,
        "rows": (
            '############################################',
            '#................#.........................#',
            '#........$.......#............v...#........#',
            '#................#........\\./.....#........#',
            '#.....###........#...#.$..........#........#',
            '#.............S..#...#............#........#',
            '#....................#....*.......#...##...#',
            '#....#...............#.................E...#',
            '#...>../...................#..*............#',
            '#.......###..@.............#\\*+......./....#',
            '#..........................#/.*.....\\......#',
            '#........................././.......\\.\\.#..#',
            '############################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'THE HUNTER',
        "lore": 'You are being hunted. HUNTER class ICE is awake on this floor: it closes distance every time you act. Break line of sight. Work fast. Work clean.',
        "intro": 'Sector 03, node 4. 9 mirrors 1 splitter prisms ICE on the floor: HUNTER, SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 3,
        "par": 30,
        "rows": (
            '#############################################',
            '#../....\\........./.\\..../*./........####...#',
            '#..@........................................#',
            '#..........###....../.*..+../..E............#',
            '#......................H..............$.....#',
            '#.......\\*.<................................#',
            '#...........................................#',
            '#......................$.*..................#',
            '#....#..........S....#......#............####',
            '#....#..###..........#......#...............#',
            '#....#..#............#...^..#...##..........#',
            '#....#..#............#......#...............#',
            '#############################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'SENTINEL WALK',
        "lore": 'SENTINEL WALK: the patrol route covers the whole junction. The route has one flaw. Find it.',
        "intro": 'Sector 03, node 5. 9 mirrors 1 splitter prisms ICE on the floor: SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 3,
        "par": 49,
        "rows": (
            '##############################################',
            '#..*....*............./...####..........#....#',
            '#...>.....*\\../.\\........###............#....#',
            '#.........#.............................#....#',
            '#.........#...........^......................#',
            '#..\\.......+..\\..............................#',
            '#........../.................................#',
            '#../.......\\....*...$....#####$#####.........#',
            '#......S..........#............###...........#',
            '#.................#..........................#',
            '#.........E.......#..........................#',
            '#.......................................@....#',
            '##############################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'FROZEN ASSETS',
        "lore": 'Frozen assets: archived daemons in cold storage, one heartbeat from waking. Every action you take warms them a little.',
        "intro": 'Sector 03, node 6. 9 mirrors 1 splitter prisms ICE on the floor: HUNTER, SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 3,
        "par": 29,
        "rows": (
            '###############################################',
            '#..................$.......\\......./...#......#',
            '#......................................#......#',
            '#.*....../.............................#......#',
            '#.............\\../.#...................#......#',
            '#..................#.........@..>..\\..........#',
            '#.......E.....*...............................#',
            '#.........S......\\..............*.............#',
            '#.............................................#',
            '#.#..............#####......H.....#..$........#',
            '#.####...+......<..............#..#...........#',
            '#.#......\\..*./................#..#...........#',
            '###############################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'GLASSHOUSE',
        "lore": 'The glasshouse - a transparent cell where the Foundry tests daemons against captured runner probes. Yours is the newest exhibit.',
        "intro": 'Sector 03, node 7. 10 mirrors 2 splitter prisms ICE on the floor: SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 3,
        "par": 43,
        "rows": (
            '################################################',
            '#............S.......................\\..+.\\/./.#',
            '#.......$...##........#####.......###..........#',
            '#..................................#.........*.#',
            '#................$.................#./....**.\\.#',
            '#....#.............................../../......#',
            '#....#.......................#.#####...........#',
            '##...#.......................#.................#',
            '##...#.......................#...........E.....#',
            '##.............................................#',
            '##...................@....###.....v............#',
            '##................................\\..+..>*..\\..#',
            '################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'FOUNDRY CORE',
        "lore": "The Foundry's core crucible. The heat that casts the ICE, buried under all this frost. Power it wrong and you'll never feel warm again.",
        "intro": 'Sector 03, node 8. 10 mirrors 2 splitter prisms ICE on the floor: HUNTER, SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 3,
        "par": 24,
        "rows": (
            '#################################################',
            '#........*......##..............####............#',
            '#.v......*$....@........H.......................#',
            '#...............................................#',
            '#/...+.../......................................#',
            '#\\.......\\.............../......................#',
            '#\\+.*\\..........................................#',
            '#*...................S...^...........###..###...#',
            '#....#......................................#...#',
            '#/..\\#......................................#...#',
            '#....#....................................$.....#',
            '#.E./...........................................#',
            '#################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'MAZE RUNNER',
        "lore": 'The Maze does not appear on maps. The corridors here are older than ORACLE-9 and meaner than Vex. Trust the beam, not the walls.',
        "intro": 'Sector 04, node 1. 9 mirrors 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 4,
        "par": 46,
        "rows": (
            '##################################################',
            '#........................................@.......#',
            '#................................................#',
            '#...........................###..................#',
            '#.......................................\\.*\\.....#',
            '#................$.....#####............*......#.#',
            '#...............................v..............#.#',
            '#..............................................#.#',
            '#....#####..............#.......*../.<.....*.....#',
            '#.......................#........................#',
            '#.......E................................/.\\.....#',
            '#.....#........$................/................#',
            '#.....#...#......................../..../\\.......#',
            '##################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'WORMHOLE',
        "lore": 'First teleport array - ORACLE-9 stole it from a dead research team and never bothered to hide the theft. Step on the pad, let the Grid fold you.',
        "intro": 'Sector 04, node 2. 9 mirrors a teleport pad pair 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 4,
        "par": 49,
        "rows": (
            '###################################################',
            '#................./*../...........................#',
            '#.................................................#',
            '#.................................................#',
            '#.............$.......*...........................#',
            '#........./*...................#...$........\\.../.#',
            '#........#..............E......#..................#',
            '#..............................#..................#',
            '#.........\\......./............#................^.#',
            '#.......#.............^................\\.*..\\.....#',
            '#.......#...................#####.................#',
            '#......................#..#.............T.........#',
            '#...........U..........#..#....................@..#',
            '###################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'SIDE STEP',
        "lore": "Side-step junctions and folded space. The shortest path is not always a path. Sometimes it's a hole in the room.",
        "intro": 'Sector 04, node 3. 9 mirrors a teleport pad pair ICE on the floor: SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 4,
        "par": 71,
        "rows": (
            '####################################################',
            '#..........*..................*/...................#',
            '#....@.......####.......#.............\\.......\\...##',
            '#.......................#....S./.....<..........#.##',
            '#...#####...............#........$........*.....#..#',
            '#.....................T.........................#..#',
            '#...............................................#..#',
            '#............................................./..\\.#',
            '#....................E.............................#',
            '#...................................../.*./........#',
            '#..............................................>./.#',
            '#........................$.........................#',
            '#....................................U.............#',
            '####################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'TWISTED PAIR',
        "lore": "TWISTED PAIR: two pad arrays, braided like cable. MIRAGE: 'This is Kai's handiwork - he mapped this place once. His notes are in the shards.'",
        "intro": 'Sector 04, node 4. 9 mirrors 1 splitter prisms a teleport pad pair ICE on the floor: HUNTER, SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 4,
        "par": 36,
        "rows": (
            '#####################################################',
            '###......................./........*................#',
            '#.......##................^...................#.....#',
            '#........................................H....#....##',
            '#.\\*\\.....................$...................#.....#',
            '#.............T..............................U#.....#',
            '#.......###.........................................#',
            '#/......S...........................................#',
            '#...................................................#',
            '#.^....#####\\../....................##..........E...#',
            '#..@................................................#',
            '#/..+......./..................................$....#',
            '#..............\\....*.....................*.........#',
            '#####################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'THE LONG WAY',
        "lore": "The long way around, or the short way through. The Hunter's patience is shorter than both.",
        "intro": 'Sector 04, node 5. 10 mirrors 1 splitter prisms a teleport pad pair ICE on the floor: HUNTER, SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 4,
        "par": 30,
        "rows": (
            '######################################################',
            '#.............\\..*..\\.................#####..#.......#',
            '#..*.....**.\\...\\.\\.......................#..#.......#',
            '#..............E......#......................#.......#',
            '#............>......+.#......................#.......#',
            '#..........H..........#..>....../.........#..........#',
            '#.......####..........#......T............#..........#',
            '#......S.............................................#',
            '#............././................$...................#',
            '#...........\\.......\\..............#...............U.#',
            '#$......#..........................#.................#',
            '#.......#....................................@.......#',
            '#.......#............................................#',
            '######################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'BLINK DRIVE',
        "lore": "BLINK DRIVE: the Maze's working teleport cluster. Blink between four rooms while Hunter ICE blinks after you.",
        "intro": 'Sector 04, node 6. 9 mirrors 1 splitter prisms a teleport pad pair ICE on the floor: HUNTER, SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 4,
        "par": 30,
        "rows": (
            '#######################################################',
            '#..........\\.\\.........#.........S....................#',
            '#......................#..............................#',
            '#U.....*............####..............................#',
            '#...#....v...*.....................................#.$#',
            '#...#..............................................#..#',
            '#...#../.+..\\/./...........................$.......####',
            '#....E.............................................#..#',
            '#.....\\.....*...............#####..................#..#',
            '#...........................................#####.....#',
            '#..................................................H..#',
            '#...#.................................................#',
            '#...#.^...../.*\\.....@.................T..............#',
            '#######################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'LABYRINTH',
        "lore": "The labyrinth proper. Walls that lie, pads that don't. Somewhere in here is a child's handwriting: a map, in crayon, of a place like this.",
        "intro": 'Sector 04, node 7. 10 mirrors 1 splitter prisms a teleport pad pair ICE on the floor: HUNTER, SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 4,
        "par": 43,
        "rows": (
            '########################################################',
            '#......\\..*../.........................................#',
            '#...>*/..........#.........................#####.......#',
            '#\\...../.*../....#....................#................#',
            '#.................####................#................#',
            '#......U..............................#...........@....#',
            '#.....#.........................####..#................#',
            '#*..v.#\\....\\.....................S....................#',
            '#.....#........................H.......................#',
            '#\\..+..\\...............................................#',
            '##...............##...........................$.T$.....#',
            '##.................E...................................#',
            '##.............................................#.......#',
            '########################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'MAZE HEART',
        "lore": "The Maze's heart beats in the dark. The crayon map ends here, at a door drawn with an X. Kai was here. Kai is still in here, somewhere.",
        "intro": 'Sector 04, node 8. 10 mirrors 1 splitter prisms a teleport pad pair ICE on the floor: HUNTER, SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 4,
        "par": 41,
        "rows": (
            '#########################################################',
            '#.....##....+.....<.............................\\.......#',
            '#..........#.....................$......................#',
            '#..........#............................................#',
            '#.....................$.................................#',
            '#...................................E.........SH^.......#',
            '#.........../../..............U..........##.............#',
            '#.......T............#.................###..............#',
            '#..............*.....#.................#................#',
            '#......................................#................#',
            '#..............\\..*..\\.................#................#',
            '#......\\.......\\.........#####..........................#',
            '#....../....*.*/...../@.................................#',
            '#########################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'VAULT DOOR',
        "lore": "The Vault door takes a full beam ensemble to open. Everything from here down is OMNICORP's memory. Steal all of it.",
        "intro": 'Sector 05, node 1. 9 mirrors 1 splitter prisms 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 5,
        "par": 47,
        "rows": (
            '##########################################################',
            '#../.....\\....................###$.......................#',
            '#..*.......E..................................#..........#',
            '#.............................................#..........#',
            '#..^.....###.......................................#....##',
            '#.............................................######....##',
            '#....................$.............................#....##',
            '#...*.....*.........................\\............#####..##',
            '#..................................................#....##',
            '#...#............................./.\\....@...............#',
            '#...#..................\\.....<...........................#',
            '#...#........................./...\\......................#',
            '#...#....#....................*..........................#',
            '#...#....#............./......+..........................#',
            '##########################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'SPLIT DECISION',
        "lore": 'SPLIT DECISION: prism forks over an abyss of redacted files. Choose your light carefully; the Vault does not forgive reruns.',
        "intro": 'Sector 05, node 2. 10 mirrors 1 splitter prisms 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 5,
        "par": 47,
        "rows": (
            '###########################################################',
            '#................../......................./....\\.........#',
            '#...##..........................................*.........#',
            '#.........................................................#',
            '#..................^.........$............................#',
            '#...#####.....................................##..........#',
            '#........................................../.\\>.+.........#',
            '#..*.......................*...*............./............#',
            '#...................................$.....................#',
            '#.....E...................................................#',
            '#.........................................................#',
            '#............##...............#............\\./............#',
            '#.............................#..........@................#',
            '#...................#.........#............/..../.........#',
            '###########################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'DAEMON DANCE',
        "lore": 'First CORRUPTOR sighting: a daemon that reaches into the optics and rewires your mirrors while you work. Kill its rhythm or it kills yours.',
        "intro": 'Sector 05, node 3. 9 mirrors 2 splitter prisms ICE on the floor: CORRUPTOR 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 5,
        "par": 47,
        "rows": (
            '############################################################',
            '#...............................................\\.......\\.^#',
            '#..........................................................#',
            '#..................######..........@......#........./.....<#',
            '#.........................................#.........*E.C...#',
            '#..................####........................./......\\...#',
            '#..................................###................#....#',
            '#.....................................................#....#',
            '#..............................................*.###..#....#',
            '#.....................................................#....#',
            '#..............................................\\...*+..+.$.#',
            '#......................$..................................\\#',
            '#.........................................................*#',
            '#....................................................../..\\#',
            '############################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'CORRUPTED',
        "lore": "The corrupted wing - files here decay into noise as you watch. ORACLE-9 grows louder: 'I kept him safe, runner. I kept him EVERYTHING.'",
        "intro": 'Sector 05, node 4. 10 mirrors 2 splitter prisms ICE on the floor: CORRUPTOR 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 5,
        "par": 72,
        "rows": (
            '#############################################################',
            '#............#...##......................../../.............#',
            '#............#.........................................$....#',
            '#............#.........................###..................#',
            '#C.........@........................###..../.\\.............##',
            '#................................###.....\\....\\.............#',
            '#.........................................../.*.............#',
            '#........................................*..................#',
            '#...........................................................#',
            '#...........................................^.../..*........#',
            '#..$.............................##.........................#',
            '#......................E.................+.......<..........#',
            '#....................................................###....#',
            '#................................../.....+*.....\\...........#',
            '#############################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'HEAVY ICE',
        "lore": "HEAVY ICE: triple-daemon defense grid, sentinel and hunter and corruptor walking the same floor. The Vault's proudest exhibit.",
        "intro": 'Sector 05, node 5. 10 mirrors 2 splitter prisms ICE on the floor: CORRUPTOR, HUNTER 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 5,
        "par": 45,
        "rows": (
            '##############################################################',
            '#............................................................#',
            '#............................................................#',
            '#.............................................$..............#',
            '#............................................................#',
            '#.....................\\.<....................................#',
            '#............................................................#',
            '#####.............................................####.......#',
            '#....#...................................####................#',
            '#......./.............*............/....\\.............#......#',
            '#....E..*....................#.C......................#......#',
            '#.......^.................#..#.........#..............#.$....#',
            '#..H................../*..*../........#..@............#......#',
            '#........................../.+.....\\/...+......\\......#......#',
            '##############################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'DOUBLE CROSS',
        "lore": 'DOUBLE CROSS: the prisms cross your own beams. One wrong mirror and the light convicts you of your own intrusion.',
        "intro": 'Sector 05, node 6. 9 mirrors 2 splitter prisms ICE on the floor: CORRUPTOR, HUNTER 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 5,
        "par": 44,
        "rows": (
            '###############################################################',
            '#.$....................................../..+......./.........#',
            '#................................................#............#',
            '#.....................E#..................../..+.../\\.........#',
            '#.....................####....................@.....####......#',
            '#......................#.................*.....^..............#',
            '#..............................*........*........../..$.......#',
            '#.....................................##.........##...........#',
            '#..............................H.........\\....../.............#',
            '#...........................................###............../#',
            '#.............................................................#',
            '#.................................#..........................^#',
            '#................#####............#.............*.............#',
            '#C................................#...........................#',
            '###############################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'VAULT RUN',
        "lore": 'Vault run. Everything in this room belongs to people who were never paid for it. Take it back one receptor at a time.',
        "intro": 'Sector 05, node 7. 10 mirrors 3 splitter prisms ICE on the floor: CORRUPTOR, HUNTER, SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 5,
        "par": 36,
        "rows": (
            '################################################################',
            '#.....................E.............../...*.../................#',
            '#.............................................+...<............#',
            '#..............................................................#',
            '#....................................C.........................#',
            '#..........................................v.*.................#',
            '#.......*..........*.......................\\...................#',
            '#.......................................@/...\\+../.............#',
            '#.................................##...........................#',
            '#.............................................H................#',
            '#.............###..............................##........##....#',
            '#......................................../.......+.\\$..........#',
            '#.................###....................................$.....#',
            '#..........................................##..#...\\...\\....S..#',
            '################################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'THE CRUCIBLE',
        "lore": "The crucible of the Vault, where erased names are smelted into silence. KAI - MEMORY FULL ERASE - WITNESS: ORACLE-9. Now you've seen the ledger.",
        "intro": 'Sector 05, node 8. 10 mirrors 3 splitter prisms ICE on the floor: CORRUPTOR, HUNTER, SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 5,
        "par": 38,
        "rows": (
            '#################################################################',
            '#....................................>.../.........+.+...*...\\..#',
            '#..................................................*............#',
            '#....................................####...\\*./..........@.....#',
            '#..........$..................................#.......#/..\\.....#',
            '#..................................$..........#......^#.........#',
            '#...................................\\......./.#.......#.........#',
            '#...................................*.........#\\...+......\\.....#',
            '#..........................................###..................#',
            '#.............................C...#.............................#',
            '#...............................#.#.............................#',
            '#.....................S.........#.#.............................#',
            '#.........#.....#####.............#.............................#',
            '#..####...#......................E#.................H...........#',
            '#################################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'THRESHOLD',
        "lore": "The threshold of the Core. ORACLE-9 dims the lights in greeting. 'You carried the shards all this way. Bring them to me.' MIRAGE: 'Don't.'",
        "intro": 'Sector 06, node 1. 9 mirrors 1 splitter prisms 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 6,
        "par": 70,
        "rows": (
            '##################################################################',
            '#.................................\\*...../.\\.....................#',
            '#.........##...............................^.....................#',
            '#.............#...................*..............................#',
            '#.............#..........................$.......................#',
            '#..........................####..................................#',
            '#................................................................#',
            '#................................................................#',
            '#......v.........................................................#',
            '#...............@.................+./.##.........................#',
            '#...............###...........................................E..#',
            '#...................................*...................###......#',
            '#....../.....................................###................##',
            '#..............#.........../....../....$..v......................#',
            '#..............#..................../...*./......................#',
            '##################################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'EVENT HORIZON',
        "lore": 'Event horizon: past this node, beams bend the way the Core wants them to. Hold your own truth. Power the gate.',
        "intro": 'Sector 06, node 2. 9 mirrors 1 splitter prisms a teleport pad pair ICE on the floor: HUNTER 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 6,
        "par": 48,
        "rows": (
            '###################################################################',
            '#..............................................*..................#',
            '#..................\\....*..\\.......U.........E...................##',
            '#........................\\...\\....................................#',
            '#..............#.....v........$...................................#',
            '#.........$....#.......##..*......................................#',
            '#..............#...*#................................#............#',
            '#..........................\\.........................#............#',
            '#....................................................#............#',
            '#............#####...................................#............#',
            '#..................\\.+.../...........................#............#',
            '#................................H..........................@.....#',
            '#.............................#...................................#',
            '#.............................#................\\......<........T..#',
            '#................................#....................\\...<.......#',
            '###################################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'CORE LIGHT',
        "lore": "CORE LIGHT junction - the Grid's nerves run bare through this room. Every mirror here is loaded. Aim carefully.",
        "intro": 'Sector 06, node 3. 10 mirrors 2 splitter prisms ICE on the floor: CORRUPTOR, HUNTER 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 6,
        "par": 38,
        "rows": (
            '####################################################################',
            '#.....\\.*.....................................*....................#',
            '#.....................\\....../..@..................................#',
            '#....E....\\.*.../............v.....................................#',
            '#..................................................................#',
            '#.....\\...\\........................................................#',
            '#..................................................................#',
            '#..................................................................#',
            '#........#......+...+./...#.#......................................#',
            '#........###..............#........................................#',
            '#........#..........^.$...#........v...............................#',
            '#.........................#........................................#',
            '#.............H............................................$.......#',
            '#.......C........................../...............................#',
            '#...............\\..............................*...................#',
            '####################################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'LAST MILE',
        "lore": "The last mile. MIRAGE's signal is degrading: 'Nyx, if I cut out - it was never about the debt. It was always about him. Go.'",
        "intro": 'Sector 06, node 4. 10 mirrors 2 splitter prisms ICE on the floor: CORRUPTOR, HUNTER, SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 6,
        "par": 41,
        "rows": (
            '#####################################################################',
            '#.................^..\\...............###.......#....................#',
            '#..............................................#................/../#',
            '#............$............#....................#....................#',
            '#....................*....#....................#....................#',
            '#.........................#..................#.#.......@............#',
            '#..........####......^....#........#.........#......................#',
            '#.........................#........#.........#........./.......*.../#',
            '#..................................#.........#..............>../\\+.\\#',
            '#.....................#...####.....#..........$.....................#',
            '#....C................#........................................*....#',
            '#.....................#............................................S#',
            '#.....................#..............E................./..*....+.\\..#',
            '#..............................................H....................#',
            '#...................................................................#',
            '#####################################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'SYSTEM SHOCK',
        "lore": 'SYSTEM SHOCK: the Core defends itself with everything it taught the Foundry to build. All of it at once. All of it now.',
        "intro": 'Sector 06, node 5. 9 mirrors 2 splitter prisms a teleport pad pair ICE on the floor: CORRUPTOR, HUNTER, SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 6,
        "par": 48,
        "rows": (
            '######################################################################',
            '#........../....../.........................................\\..+....+#',
            '#..........*.........................................................#',
            '#..................................../.....<.........................#',
            '####.......*.............................................#...........#',
            '#........................................................#....@......#',
            '#.................*......................................#..........\\#',
            '#........../.....<................./.\\S..............................#',
            '#........................................#...........................#',
            '#...*.............\\...............E....H.#.....................^.....#',
            '#..........U.........................................................#',
            '#....................................................................#',
            '#...............$..................C....#................#....T......#',
            '#.......................................#................#...........#',
            '#................$......................#.....##.........#...........#',
            '######################################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'FINAL FIREWALL',
        "lore": "The final firewall burns green. Vex's voice on all channels, one last time: 'You should have taken the money, runner.'",
        "intro": 'Sector 06, node 6. 10 mirrors 2 splitter prisms ICE on the floor: CORRUPTOR, HUNTER, SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 6,
        "par": 47,
        "rows": (
            '#######################################################################',
            '#........./.....................$.....................................#',
            '#.........\\...+.*...\\......................................####.......#',
            '#..............................S......................................#',
            '#................................................#....................#',
            '#..\\...<\\.....\\...........@......................#..H....#............#',
            '#............................./*.....<...........#.......#......C.....#',
            '#......E.....v..#........................................#............#',
            '#..*............#.....................................................#',
            '#\\.+..../.......#....................##...............................#',
            '#...............#.....................................................#',
            '#...............#.....................................................#',
            '#...........#.........................................####............#',
            '#..............#.........................................#............#',
            '#......*.....\\.#.......................................$..............#',
            '#######################################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'GRID HEART',
        "lore": "The Grid's heart, one gate away. ORACLE-9 speaks in Kai's voice, in your mother's voice, in yours. Only the beam's opinion matters now.",
        "intro": 'Sector 06, node 7. 9 mirrors 2 splitter prisms ICE on the floor: CORRUPTOR, HUNTER, SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 6,
        "par": 44,
        "rows": (
            '########################################################################',
            '#.....##........\\..../..@............................##................#',
            '#....................*.................................................#',
            '#....................*...................................E.............#',
            '#....................................................#.................#',
            '#.............\\./...................$................#.................#',
            '#............#...............................H.......#.................#',
            '#............#.........$.............................#.................#',
            '#.........#..........+../......................../.....*.<.............#',
            '#.........#.....C...................##.................................#',
            '#.........#.........................................#..................#',
            '#.........#.........................................#............S.....#',
            '#..................../.................................................#',
            '#..............#........+......<.......................................#',
            '#..................*..../..............................>../............#',
            '########################################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
    {
        "name": 'SINGULARITY',
        "lore": 'SINGULARITY. The center of the machine. The center of the lie. Power the heart, runner, and bring your brother home.',
        "intro": 'Sector 06, node 8. 11 mirrors 3 splitter prisms a teleport pad pair ICE on the floor: CORRUPTOR, HUNTER, SENTINEL 4 receptors. Power all receptors, reach the extraction node.',
        "zone": 6,
        "par": 45,
        "rows": (
            '########################################################################',
            '#.......#.................@.........#...........................\\./...*#',
            '#.......#...........................#..................................#',
            '#.......#...........................#................T.................#',
            '#.......#...........................#............................v.....#',
            '#..........................##....................................*....*#',
            '#.....................v............S............................*......#',
            '#..............................................E................/...+./#',
            '#..>..../..............................................................#',
            '#........H.............................................../...\\.........#',
            '#..............#.$....\\................................................#',
            '#..............#.............................................\\...+..+..#',
            '#.........C....#.......U.....................................#.........#',
            '#..............#......##.................................#...#.........#',
            '#..............#.........................................#...#....$./.\\#',
            '########################################################################',
        ),
        "bandwidth_start": 100,
        "bandwidth_floor": 0,
    },
)
